export const GET_SUBCRIPTION_BEGIN = "GET_SUBCRIPTION_BEGIN";
export const POST_OTP_LOGIN_BEGIN = "POST_OTP_LOGIN_BEGIN";
export const POST_OTP_LOGIN_SUCCESS = "POST_OTP_LOGIN_SUCCESS";
export const BUYSUBSCRIPTION_BEGIN = "BUYSUBSCRIPTION_BEGIN";

export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";

export const GETDATA_BEGIN = "GETDATA_BEGIN";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_ERROR = "GETDATA_ERROR";
